# 'esphome --dashboard run ./firmwareV4/led-digit.yaml --device OTA
esphome:
  name: seven-seg-four-digits-binah
  friendly_name: Binah Clock

esp8266:
  board: d1_mini

# Add this time component
time:
  - platform: sntp
    id: sntp_time
    timezone: America/Edmonton # Change this to your timezone

logger:

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

light:
  - platform: neopixelbus
    id: led_strip
    name: "LED Strip"
    type: RGB
    pin: GPIO4
    num_leds: 39
    variant: WS2812
    default_transition_length: 0s
    restore_mode: ALWAYS_ON
    on_turn_on:
      then:
        - light.turn_on:
            id: led_strip
            effect: "Show Time"
    effects:
      - addressable_lambda:
          name: "Show Time"
          update_interval: 16ms
          lambda: |-
            static const Color sign_color = Color(255, 120, 255);
            static const Color off_color = Color(0, 0, 0);
            
            // Get current time components
            auto time = id(sntp_time).now();
            int hours = time.hour;
            if (hours > 12) {
              hours -= 12;
            } else if (hours == 0) {
              hours = 12;
            }
            int minutes = time.minute;
            
            // Simplified pulsing calculation with logging
            float pulse_brightness = (sin(millis() * M_PI / 1000.0f) + 1.0f) / 2.0f;
            int r = sign_color.red * pulse_brightness;
            int g = sign_color.green * pulse_brightness;
            int b = sign_color.blue * pulse_brightness;
            Color pulse_color = Color(r, g, b);
            
            // Log values every second
            static uint32_t last_log = 0;
            if (millis() - last_log > 1000) {
              ESP_LOGI("PULSE", "Brightness: %.2f, Color(R:%d, G:%d, B:%d)", 
                       pulse_brightness,
                       pulse_color.red,
                       pulse_color.green,
                       pulse_color.blue);
              last_log = millis();
            }

            // Keep your existing SEGMENTS array and display_digit function exactly as they are
            static const uint8_t SEGMENTS[10][8] = {
              {1, 0, 1, 1, 1, 1, 0, 1},    // 0
              {0, 0, 0, 1, 0, 0, 0, 1},    // 1
              {1, 1, 1, 0, 0, 1, 1, 1},    // 2
              {0, 1, 1, 1, 0, 1, 1, 1},    // 3
              {0, 1, 0, 1, 1, 0, 1, 1},    // 4
              {0, 1, 1, 1, 1, 1, 1, 0},    // 5
              {1, 1, 1, 1, 1, 1, 1, 0},    // 6
              {0, 0, 0, 1, 0, 1, 0, 1},    // 7
              {1, 1, 1, 1, 1, 1, 1, 1},    // 8
              {0, 1, 1, 1, 1, 1, 1, 1}     // 9
            };

            // Function to display a number at a specific digit position
            auto display_digit = [&](int bottom_start, int top_start, int number) {
              if (number < 0 || number > 9) return;
              
              // Bottom row LEDs
              it[bottom_start].set(SEGMENTS[number][0] ? sign_color : off_color);      // i
              it[bottom_start + 1].set(SEGMENTS[number][1] ? sign_color : off_color);  // ii
              it[bottom_start + 2].set(SEGMENTS[number][2] ? sign_color : off_color);  // iii
              it[bottom_start + 3].set(SEGMENTS[number][3] ? sign_color : off_color);  // iv
              
              // Top row LEDs
              it[top_start].set(SEGMENTS[number][4] ? sign_color : off_color);      // v
              it[top_start - 1].set(SEGMENTS[number][5] ? sign_color : off_color);  // vi
              it[top_start - 2].set(SEGMENTS[number][6] ? sign_color : off_color);  // vii
              it[top_start - 3].set(SEGMENTS[number][7] ? sign_color : off_color);  // viii
            };

            // Clear all LEDs first
            for (int i = 0; i < it.size(); i++) {
              it[i].set(off_color);
            }

            // Display hours and minutes using your working LED positions
            if (hours < 10) {
              // Hours < 10, leave first digit blank
              display_digit(4, 31, hours);          // Hours in ones position
            } else {
              // Hours 10-12, show both digits
              display_digit(0, 35, hours / 10);     // Hours tens
              display_digit(4, 31, hours % 10);     // Hours ones
            }

            // Always show both digits for minutes
            display_digit(10, 25, minutes / 10);    // Minutes tens
            display_digit(14, 21, minutes % 10);    // Minutes ones

            // Update colon and last three LEDs to use pulse color
            it[8].set(pulse_color);    // First colon bottom
            it[27].set(pulse_color);   // Second colon bottom

            // Set the pulsing LEDs (last three LEDs)
            it[36].set(pulse_color);
            it[37].set(pulse_color);
            it[38].set(pulse_color);
