esphome:
  name: seven-seg-test
  friendly_name: Seven Segment Test

esp8266:
  board: d1_mini

logger:

# Add OTA configuration
ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Seven-Seg-Test"
    password: "configureme"

light:
  - platform: neopixelbus
    type: RGB
    pin: GPIO4
    num_leds: 45
    name: "LED Strip"
    id: led_strip
    variant: WS2812
    default_transition_length: 0s
    restore_mode: ALWAYS_ON
    on_turn_on:
      then:
        - light.turn_on:
            id: led_strip
            effect: "Segment Test"
    effects:
      - addressable_lambda:
          name: "Segment Test"
          update_interval: 500ms
          lambda: |-
            static int current_digit = 0;

            static const Color sign_color = Color(0, 255, 255);
            auto displayDigit = [&](int digit, int displayUnit, int ledsPerDigit = 7) {
              // Calculate the starting LED index for this display unit
              static const int DISPLAY_UNIT_INDICES[] = {0, 7, 17, 24, 31, 38};
              int baseIndex = (displayUnit >= 0 && displayUnit < 6) ? DISPLAY_UNIT_INDICES[displayUnit] : 0;
              
              // Clear this display unit's LEDs
              for (int i = baseIndex; i < baseIndex + ledsPerDigit; i++) {
                it[i] = Color(0, 0, 0);
              }
              
              // Arrays defining which segments are lit for each digit
              static const uint8_t SEGMENTS[10][7] = {
                {1, 1, 1, 0, 1, 1, 1},    // 0
                {0, 1, 0, 0, 0, 1, 0},    // 1
                {1, 0, 1, 1, 0, 1, 1},    // 2
                {1, 1, 0, 1, 0, 1, 1},    // 3
                {0, 1, 0, 1, 1, 1, 0},    // 4
                {1, 1, 0, 1, 1, 0, 1},    // 5
                {1, 1, 1, 1, 1, 0, 1},    // 6
                {0, 1, 0, 0, 0, 1, 1},    // 7
                {1, 1, 1, 1, 1, 1, 1},    // 8
                {1, 1, 0, 1, 1, 1, 1}     // 9
              };
              
              // Set the appropriate segments for the digit
              if (digit >= 0 && digit <= 9) {
                for (int segment = 0; segment < 7; segment++) {
                  if (SEGMENTS[digit][segment]) {
                    switch(displayUnit) {
                      case 0:
                        it[baseIndex + segment] = Color(255, 0, 255);  // Purple
                        break;
                      case 1:
                        it[baseIndex + segment] = Color(0, 255, 255);  // Cyan
                        break;
                      case 2:
                        it[baseIndex + segment] = Color(255, 255, 0);  // Yellow
                        break;
                      case 3:
                        it[baseIndex + segment] = Color(255, 106, 150);    // Green
                        break;
                    }
                  }
                }
              }
            };

            // Display the current digit on all six displays
            displayDigit(current_digit, 0);
            displayDigit(current_digit, 1);
            displayDigit(current_digit, 2);
            displayDigit(current_digit, 3);
            displayDigit(current_digit, 4);
            displayDigit(current_digit, 5);

            // Handle colon LEDs (assuming they're at indices 14, 15, 16 and 28, 29, 30)
            static const int COLON_LEDS[] = {14, 16, 28, 30};
            for (int i : COLON_LEDS) {
              it[i] = sign_color;  // Set colon to same brightness
            }
            it[15] = Color(0, 0, 0);  // Turn off middle LED of first colon
            it[29] = Color(0, 0, 0);  // Turn off middle LED of second colon

            // Increment the counter
            current_digit = 6;
