esphome:
  name: six-digit-clock
  friendly_name: Six Digit Clock

esp8266:
  board: d1_mini
# Add time component after logger:
time:
  - platform: sntp
    id: sntp_time
    timezone: America/Edmonton # Change this to your timezone

logger:

# Add OTA configuration
ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Seven-Seg-Test"
    password: "configureme"

light:
  - platform: neopixelbus
    type: RGB
    pin: GPIO4
    num_leds: 48
    name: "LED Strip"
    id: led_strip
    variant: WS2812
    default_transition_length: 0s
    restore_mode: ALWAYS_ON
    on_turn_on:
      then:
        - light.turn_on:
            id: led_strip
            effect: "Show Time"
    effects:
      - addressable_lambda:
          name: "Show Time"
          update_interval: 1000ms
          lambda: |-
            // Define gradient colors - Pink to Light Blue
            static const Color gradient_colors[7] = {
              Color(255, 20, 147),   // Deep Pink (bottom segments)
              Color(255, 69, 180),   // Pink
              Color(255, 105, 200),  // Light Pink
              Color(200, 162, 235),  // Lavender (middle)
              Color(135, 206, 250),  // Light Sky Blue
              Color(100, 220, 255),  // Light Blue
              Color(173, 216, 230)   // Light Blue (top segments)
            };
            
            auto displayDigit = [&](int digit, int displayUnit, int ledsPerDigit = 7) {
              // Calculate the starting LED index for this display unit
              static const int DISPLAY_UNIT_INDICES[] = {0, 7, 17, 24, 34, 41};
              int baseIndex = (displayUnit >= 0 && displayUnit < 6) ? DISPLAY_UNIT_INDICES[displayUnit] : 0;
              
              // Clear this display unit's LEDs
              for (int i = baseIndex; i < baseIndex + ledsPerDigit; i++) {
                it[i] = Color(0, 0, 0);
              }
              
              // Arrays defining which segments are lit for each digit
              static const uint8_t SEGMENTS[10][7] = {
                {1, 1, 1, 0, 1, 1, 1},    // 0
                {0, 1, 0, 0, 0, 1, 0},    // 1
                {1, 0, 1, 1, 0, 1, 1},    // 2
                {1, 1, 0, 1, 0, 1, 1},    // 3
                {0, 1, 0, 1, 1, 1, 0},    // 4
                {1, 1, 0, 1, 1, 0, 1},    // 5
                {1, 1, 1, 1, 1, 0, 1},    // 6
                {0, 1, 0, 0, 0, 1, 1},    // 7
                {1, 1, 1, 1, 1, 1, 1},    // 8
                {1, 1, 0, 1, 1, 1, 1}     // 9
              };
              
              // Set the appropriate segments for the digit with gradient colors
              if (digit >= 0 && digit <= 9) {
                for (int segment = 0; segment < 7; segment++) {
                  if (SEGMENTS[digit][segment]) {
                    it[baseIndex + segment] = gradient_colors[segment];
                  }
                }
              }
            };

            // Get current time
            auto time = id(sntp_time).now();
            int hours = time.hour;
            int minutes = time.minute;
            int seconds = time.second;

            // Convert to 12-hour format
            if (hours > 12) hours -= 12;
            if (hours == 0) hours = 12;

            // Display each digit of the time (skip leading zero for hours)
            if (hours >= 10) {
              displayDigit(hours / 10, 0);  // Hours tens (only if >= 10)
            } else {
              // Clear the first digit position completely for single-digit hours
              for (int i = 0; i < 7; i++) {
                it[i] = Color(0, 0, 0);
              }
            }
            displayDigit(hours % 10, 1);  // Hours ones
            displayDigit(minutes / 10, 2); // Minutes tens
            displayDigit(minutes % 10, 3); // Minutes ones
            displayDigit(seconds / 10, 4); // Seconds tens
            displayDigit(seconds % 10, 5); // Seconds ones

            // Handle colon LEDs with gradient color (middle segment color)
            static const int COLON_LEDS[] = {14, 16, 31, 33};
            for (int i : COLON_LEDS) {
              it[i] = gradient_colors[3]; // Use middle gradient color for colons
            }
            it[15] = Color(0, 0, 0);  // Turn off middle LED of first colon
            it[32] = Color(0, 0, 0);  // Turn off middle LED of second colon

